# Generated by Django 3.1.4 on 2021-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
